services:
  db-user:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: user_service
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
    volumes:
      - postgres_user_data:/var/lib/postgresql/data
    ports:
      - "15432:5432"

  db-keycloak:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_keycloak_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://db-keycloak:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_PROXY: edge
      KC_HOSTNAME: localhost
    ports:
      - "8080:8080"
      - "8443:8443"
    depends_on:
      - db-keycloak
    command: [ "start-dev" ]

#  nginx:
#    image: nginx:latest
#    ports:
#      - "8080:80"
#    volumes:
#      - ./configs/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
#      - ./logs/nginx:/var/log/nginx

  victoria-metrics:
    image: victoriametrics/victoria-metrics:v1.93.12
    container_name: victoria-metrics
    ports:
      - "8428:8428"
    command:
      - '--promscrape.config=/etc/vm/promscrape.yaml'
      - '--storageDataPath=/storage'
    volumes:
      - ./configs/victoria-metrics/promscrape.yaml:/etc/vm/promscrape.yaml:ro
      - ./configs/victoria-metrics/data:/storage

  grafana:
    image: grafana/grafana:10.2.4
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./configs/grafana:/var/lib/grafana

  trace:
    image: grafana/tempo:2.3.1
    container_name: shop-trace
    ports:
      - "3200:3200"
      - "9095:9095"
      - "4317:4317"
      - "4318:4318"
      - "9411:9411"
      - "14268:14268"
    volumes:
      - ./configs/tempo/tempo.yaml:/etc/tempo.yaml
    command:
      - '-config.file=/etc/tempo.yaml'

  grafana-loki:
    image: grafana/loki:2.9.4
    container_name: grafana-loki
    ports:
      - "3100:3100"
volumes:
  postgres_user_data:
  postgres_keycloak_data: