databaseChangeLog:
  - changeSet:
      id: 008-create-product-attribute-values
      author: dXdyZ
      changes:
        - createTable:
            tableName: product_attribute_values
            columns:
              - column:
                  name: id
                  type: BIGINT
                  autoIncrement: true
                  constraints:
                    primaryKey: true
                    primaryKeyName: pk_product_attribute_values
                    nullable: false
              - column:
                  name: public_id
                  type: UUID
                  constraints:
                    nullable: false
                    unique: true
                    uniqueConstraintName: uq_product_attribute_values_public_id
              - column:
                  name: product_id
                  type: BIGINT
                  constraints:
                    nullable: false
              - column:
                  name: attribute_value_id
                  type: BIGINT
                  constraints:
                    nullable: false
        - addForeignKeyConstraint:
            baseTableName: product_attribute_values
            baseColumnNames: product_id
            referencedTableName: products
            referencedColumnNames: id
            constraintName: fk_pav_product
            onDelete: CASCADE
        - addForeignKeyConstraint:
            baseTableName: product_attribute_values
            baseColumnNames: attribute_value_id
            referencedTableName: attribute_values
            referencedColumnNames: id
            constraintName: fk_pav_attribute_value
            onDelete: CASCADE
        - addUniqueConstraint:
            tableName: product_attribute_values
            columnNames: product_id, attribute_value_id
            constraintName: uq_pav_product_attribute_value
        - createIndex:
            indexName: idx_pav_product_id
            tableName: product_attribute_values
            columns:
              - column:
                  name: product_id
        - createIndex:
            indexName: idx_pav_attribute_value_id
            tableName: product_attribute_values
            columns:
              - column:
                  name: attribute_value_id
        - createIndex:
            indexName: idx_pav_public_id
            tableName: product_attribute_values
            unique: true
            columns:
              - column:
                  name: public_id