spring:
  config:
    activate:
      on-profile: integration
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  liquibase:
    enabled: true
    change-log: classpath:/db/db.changelog-master.yaml
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql

resilience4j:
  retry:
    instances:
      keycloakVerifyEmail:
        maxAttempts: 1
        waitDuration: 10ms
      keycloakCreateUser:
        maxAttempts: 1
        waitDuration: 10ms
        retryExceptions:
          - jakarta.ws.rs.ProcessingException
        ignoreExceptions:
          - com.shop.userservice.exception.UserDuplicateException
      keycloakDeleteUser:
        maxAttempts: 1
        waitDuration: 10ms

logging:
  level:
    root: INFO
    com.example: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.testcontainers: INFO