spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:15432/user_service
    username: user
    password: user
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:/db/db.changelog-master.yaml
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/shop
keycloak:
  server-url: http://localhost:8080
  realms:
    service-realms:
      realm: shop
    admin-realms:
      realm: master
      username: admin
      password: admin
      client:
        client-id: admin-cli
server:
  port: 9090
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
#      Какое кол-во трайсов собирать в процентах
      probability: 0.6
  metrics:
    tags:
      application: user-service

resilience4j:
  retry:
    instances:
      keycloakVerifyEmail:
        max-attempts: 5                # Общее количество попыток (1 оригинальный вызов + 4 ретрая = 5)
        wait-duration: 500ms           # Базовая задержка перед повтором (для 1-й повторной попытки)
        enable-exponential-backoff: true   # Включает экспоненциальное увеличение задержки
        exponential-backoff-multiplier: 2  # Множитель для роста задержки (500ms → 1s → 2s → 4s)
        enable-randomized-wait: true       # Добавляет случайность (джиттер), чтобы снизить нагрузку при одновременных ретраях
        randomized-wait-factor: 0.5        # Задаёт диапазон рандомизации ±50% (например, при 2s пауза будет 1s–3s)
        retry-exceptions:
          - jakarta.ws.rs.ProcessingException

        # ignore-exceptions:               # Исключения, которые не нужно ретраить (например, бизнес-ошибки)
        #   - com.example.UserDuplicateException
        # fail-after-max-attempts: true    # После исчерпания попыток выбросить исключение (иначе пойдет в fallbackMethod)
        # event-consumer-buffer-size: 100  # Размер буфера событий для метрик (если используешь Micrometer/Prometheus)
      keycloakCreateUser:
        max-attempts: 5
        wait-duration: 500ms
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2
        enable-randomized-wait: true
        randomized-wait-factor: 0.5
        retry-exceptions:
          - jakarta.ws.rs.ProcessingException
