###
POST http://localhost:9090/api/v1/registration
Content-Type: application/json

{
  "username": "Met12User",
  "lastName": "Sq12ser",
  "firstName": "sdest",
  "patronymic": "Us12ertest",
  "phoneNumber": "89005633985",
  "email": "userM12etrcis123@gmail.com",
  "password": "password"
}

###
POST http://localhost:9090/api/