spring:
  application:
    name: product-catalog-service
  elasticsearch:
    uris: http://localhost:9200
    connection-timeout: 2s
    socket-timeout: 30s
  liquibase:
    enabled: true
    change-log: classpath:/db/db.changelog-master.yaml
