spring:
  application:
    name: product-catalog-service
  elasticsearch:
    uris: http://localhost:9200
    connection-timeout: 2s
    socket-timeout: 30s
  liquibase:
    enabled: true
    change-log: classpath:/db/db.changelog-master.yaml
  jpa:
    properties:
      hibernate.jdbc.fetch_size: 1000
      hibernate.default_batch_fetch_size: 100
